name: agenda_contactos
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  path_provider: ^2.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^5.0.1

  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.1.0+3
  sqflite_common_ffi_web: ^0.4.5+4
  path: ^1.9.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_database: ^11.3.1
  firebase_messaging: ^15.2.1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true